[package]
name = "piet_wgpu_derive"
version = "0.1.0"
description = "Provides derive implementations"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
